### PR TITLE
Testing and CI relationship demo

### PR DESCRIPTION
**Pull request by lghszdnp**

### CODE REVIEW

**Comment by neilhatfield** [comment]
@lghszdnp Have you pushed updated code yet for fixing the XLSX issue?

**Comment by lghszdnp** [comment]
> @lghszdnp Have you pushed updated code yet for fixing the XLSX issue?

I have just pushed a new version with serval changes include the xlsx problem

**Comment by ethanwright3** [comment]
As far as I can tell nothing changes when working with set the alternative hypothesis. Additionally the ImportYourOwn option causes a crash though I think that's what you and Professor Hatfield are already discussing.

**Review by neilhatfield — CHANGES_REQUESTED** [review]
Here are some changes to make:

1. You don't need `library(ggplot2)` in the ui.R file.
2. You need to add `library(boastUtils)` to both ui.R and server.R
3. You are missing the app meta data section. Add.
4. Reformat the code so that you don't have so much leading white space.
    - For example, in the ui.R, you have 14 spaces between the left margin and the title comment/`dashboardHeader`. This can be greatly trimmed.
    - If you were to press return after `dashboardPage(` you'll move `skin = "purple",` to a new line. You can then line elements up with that. Only move two spaces inwards as you move into a new function. (The elements of `dashboardHeader` would be two spaces to the right of `dashboardHeader`.
5. Place spaces on both sides of `=` AND put spaces after commas to improve code readability.
6. Be explicit with argument names.
7. Resolve long lines (reformatting will help with this).
8. Fix Issue #1 
9. Fix issue #5 
    - The console should run essentially empty--"Listening on http://< IP address and port>" is ideally all that should appear.  
10. In the UI,
    - Delete line 8
    - Either delete line 15 (info button) or program what information is supposed to go there
    - Delete lines 16-17
    - Delete lines 37-42
    - Remove calls to `fluidPage` (everywhere)
    - List items MUST BE in a list environment; `p` is NOT a list environment. (Fix in all places.)
    - I would make the Explore button go to the Choose data tab (if this tab remains).
    - Organize the UI in the same order as the tabs in the sidebar.
    - The usages of `titlePanel`, `sidebarLayout`,`sidebarPanel`, `mainPanel` are outdated. Use a `fluidRow` with `column` to organize sections. Controls should be in a `wellPanel`.
    - I do not see the purpose of the separate choose a data set tab. I do not believe that there is any educational benefit to having this tab. 
        - The choosing of the data set can be moved into the Testing/CI Relationship tab.
        - The data table and data summary inner tabs can be dropped without interfering with the rest of the app.
    - What is the advantage to allowing a user to upload their own data file in this app?
    - Move `withMathJax()` out of the `fluidRow` (second argument of this `tabItem` instance)
    - Move "Conduct a test..." out of the `fluidRow` and change `h4` to `h2` (This will be your page header and third argument of this `tabItem` instance)
    - Remove lines 117-120 (This is inline CSS which is not allowed.)
    - The "How does the interval..." line should be in `p`, not `h4`.
11. In the server,
    - You've defined both `boastPalette` and `psuPalette` but I don't see where you actually use them.
        - One you define them, you can call elements with `boastPalette[3]` in your code. (This is preferred.)
    - (Crossed with UI) What are `uiOutput("var.selM")`, `uiOutput("size.selM")`, and `uiOutput("null.selM")` doing? (If they are necessary, this is a good place to add comments to your code.)
    - Convert plot.histM to a full `ggplot2` rather than `qplot`.
        - This should bring back the axes/frame
        - Increase the font size of the title, axis labels, and values on the axes

There are other issues but you have more than enough to tackle at this time.

**Comment by neilhatfield** [comment]
@lghszdnp 
Which branch is the active one?  

- Testing_and_CI_RelationshipDemo
- Testing_and_CI_Relationship

Whichever is the active one that you're going to us going forward, keep that one. Go ahead and delete the other branch. If you need to close and make a new Pull Request, please do so.

**Pull request closed without merging**
